services:
  saufi-portfolio:
    build: .
    container_name: saufi-portfolio
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: .env
    volumes:
      - ./data:/app/data
    deploy:
      resources:
        limits:
          memory: 768M
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.saufi-portfolio.rule=Host(`saufi.${DOMAIN}`)"
      - "traefik.http.routers.saufi-portfolio.entrypoints=web"
      - "traefik.http.services.saufi-portfolio.loadbalancer.server.port=3000"

networks:
  traefik-public:
    external: true
